ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER APro IDENTIFIED BY APro1234;
ALTER USER APro DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO APro;